# numpy yaratish

In [1]:
import numpy as np 

In [3]:
a1=np.array([1,3,5,7,9,11])

In [4]:
a1

array([ 1,  3,  5,  7,  9, 11])

In [7]:
a1[0]

1

In [9]:
type(a1)

numpy.ndarray

In [11]:
type(a1[0])

numpy.int32

# 2-D matritsa

In [14]:
a2=np.array([[0,2,4],[6,8,10],[12,14,16],[18,20,22]])

In [16]:
a2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [18]:
a2.shape

(4, 3)

In [20]:
a2.size

12

In [22]:
len(a2)

4

In [24]:
a2.dtype

dtype('int32')

# Numpy vs List ular ustida amallar

In [27]:
b=[2,3,5,7]

In [29]:
for i in b: 
    print(i**3)

8
27
125
343


In [31]:
b+5

TypeError: can only concatenate list (not "int") to list

In [33]:
a1

array([ 1,  3,  5,  7,  9, 11])

In [35]:
a1+5

array([ 6,  8, 10, 12, 14, 16])

In [37]:
a1

array([ 1,  3,  5,  7,  9, 11])

In [39]:
a1*9

array([ 9, 27, 45, 63, 81, 99])

In [41]:
a1**3

array([   1,   27,  125,  343,  729, 1331], dtype=int32)

In [43]:
a1[:1]

array([1])

In [45]:
a1[3:]

array([ 7,  9, 11])

In [49]:
a2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [51]:
a2[2]

array([12, 14, 16])

In [55]:
a2[2][2]

16

In [57]:
a2[1:]

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [59]:
a2[:4]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [63]:
a2[:,1]

array([ 2,  8, 14, 20])

# qator

In [66]:
a2[0]

array([0, 2, 4])

# ustun

In [72]:
a2[:,0]

array([ 0,  6, 12, 18])

In [74]:
a2.shape

(4, 3)

In [76]:
a2.reshape(6,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [78]:
a2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [80]:
a2.reshape(3,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [82]:
a2.reshape(1,12)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22]])

In [84]:
a2.reshape(12,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22]])

# time 

In [87]:
import time

In [89]:
size=1_000_000
python_list=list(range(size))
numpy_array=np.arange(size)

#  Listni vaqtini xisoblash

In [92]:
start_time=time.time()
python_list_tripled=[x**3 for x in python_list]
end_time=time.time()
python_time=end_time-start_time

# Numpy vaqtini hisoblash

In [95]:
start_time=time.time()
numpy_sqared=numpy_array**2
end_time=time.time()
numpy_time=end_time-start_time

In [97]:
print(python_time)
print(numpy_time)

0.17971205711364746
0.003021717071533203


In [99]:
python_time/numpy_time

59.4734890326653

# listni vazifalarini numpyda qullash 

# numpy yarating va unga elementlarni qo'shing

In [108]:
a3=np.array([5,6,7,15,16,17])

In [120]:
a3=np.insert(a3,1,58)

In [122]:
a3

array([ 5, 58,  6,  7, 15, 16, 17])

# numpyning uzunligini toping

In [126]:
len(a3)

7

# numpyning eng katta va eng kichik elementlarini toping

In [130]:
max(a3)

58

In [132]:
min(a3)

5

In [134]:
max(a2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [136]:
max(a2[0])

4

# numpyni teskari tartibda chiqaring

In [142]:
a3[::-1]

array([17, 16, 15,  7,  6, 58,  5])

In [144]:
a3

array([ 5, 58,  6,  7, 15, 16, 17])

In [146]:
a2[::-1]

array([[18, 20, 22],
       [12, 14, 16],
       [ 6,  8, 10],
       [ 0,  2,  4]])

# numpyni tozalang

In [155]:
a3.clear()

AttributeError: 'numpy.ndarray' object has no attribute 'clear'

In [159]:
a3

array([ 5, 58,  6,  7, 15, 16, 17])

In [163]:
a3=np.array([])

In [165]:
a3

array([], dtype=float64)